version: '3.1'

services:

  admin:
    build: .
    image: image-name:image-tag
    ports:
      - 4001:80 # 4001 is exposed port & 80 is next(container) port
    restart: always
    container_name: next-js-app